service: use-docker-with-gemfile-lock

plugins:
  - serverless-ruby-layer
custom:
  rubyLayer:
    use_docker: true

provider:
  name: aws
  runtime: ruby3.4

functions:
  hello:
    handler: handler.hello
