service: basic-ignore-gemfile-lock

plugins:
  - serverless-ruby-layer

custom:
  rubyLayer:
    ignore_gemfile_lock: true

provider:
  name: aws
  runtime: ruby3.4

functions:
  hello:
    handler: handler.hello
